// Top 1000 most common English words categorized for sentence generation
export const commonWords = {
  articles: ["the", "a", "an"],

  pronouns: [
    "i",
    "you",
    "he",
    "she",
    "it",
    "we",
    "they",
    "me",
    "him",
    "her",
    "us",
    "them",
    "my",
    "your",
    "his",
    "her",
    "its",
    "our",
    "their",
    "this",
    "that",
    "these",
    "those",
    "who",
    "what",
    "which",
    "where",
    "when",
    "why",
    "how",
    "all",
    "some",
    "many",
    "few",
    "other",
    "another",
    "any",
    "each",
    "every",
    "both",
    "either",
    "neither",
  ],

  verbs: [
    "be",
    "have",
    "do",
    "say",
    "go",
    "get",
    "make",
    "know",
    "think",
    "take",
    "see",
    "come",
    "want",
    "look",
    "use",
    "find",
    "give",
    "tell",
    "work",
    "call",
    "try",
    "ask",
    "need",
    "feel",
    "become",
    "leave",
    "put",
    "mean",
    "keep",
    "let",
    "begin",
    "seem",
    "help",
    "talk",
    "turn",
    "start",
    "show",
    "hear",
    "play",
    "run",
    "move",
    "like",
    "live",
    "believe",
    "hold",
    "bring",
    "happen",
    "write",
    "provide",
    "sit",
    "stand",
    "lose",
    "pay",
    "meet",
    "include",
    "continue",
    "set",
    "learn",
    "change",
    "lead",
    "understand",
    "watch",
    "follow",
    "stop",
    "create",
    "speak",
    "read",
    "allow",
    "add",
    "spend",
    "grow",
    "open",
    "walk",
    "win",
    "offer",
    "remember",
    "love",
    "consider",
    "appear",
    "buy",
    "wait",
    "serve",
    "die",
    "send",
    "expect",
    "build",
    "stay",
    "fall",
    "cut",
    "reach",
    "kill",
    "remain",
    "suggest",
    "raise",
    "pass",
    "sell",
    "require",
    "report",
    "decide",
    "pull",
  ],

  nouns: [
    "time",
    "person",
    "year",
    "way",
    "day",
    "man",
    "thing",
    "woman",
    "life",
    "child",
    "world",
    "school",
    "state",
    "family",
    "student",
    "group",
    "country",
    "problem",
    "hand",
    "part",
    "place",
    "case",
    "week",
    "company",
    "system",
    "program",
    "question",
    "work",
    "government",
    "number",
    "night",
    "point",
    "home",
    "water",
    "room",
    "mother",
    "area",
    "money",
    "story",
    "fact",
    "month",
    "lot",
    "right",
    "study",
    "book",
    "eye",
    "job",
    "word",
    "business",
    "issue",
    "side",
    "kind",
    "head",
    "house",
    "service",
    "friend",
    "father",
    "power",
    "hour",
    "game",
    "line",
    "end",
    "member",
    "law",
    "car",
    "city",
    "community",
    "name",
    "president",
    "team",
    "minute",
    "idea",
    "kid",
    "body",
    "information",
    "back",
    "parent",
    "face",
    "others",
    "level",
    "office",
    "door",
    "health",
    "person",
    "art",
    "war",
    "history",
    "party",
    "result",
    "change",
    "morning",
    "reason",
    "research",
    "girl",
    "guy",
    "moment",
    "air",
    "teacher",
    "force",
    "education",
  ],

  adjectives: [
    "good",
    "new",
    "first",
    "last",
    "long",
    "great",
    "little",
    "own",
    "other",
    "old",
    "right",
    "big",
    "high",
    "different",
    "small",
    "large",
    "next",
    "early",
    "young",
    "important",
    "few",
    "public",
    "bad",
    "same",
    "able",
    "human",
    "local",
    "sure",
    "better",
    "best",
    "low",
    "real",
    "free",
    "true",
    "whole",
    "major",
    "current",
    "left",
    "national",
    "possible",
    "late",
    "hard",
    "recent",
    "available",
    "easy",
    "strong",
    "special",
    "clear",
    "open",
    "red",
    "difficult",
    "certain",
    "economic",
    "black",
    "white",
    "close",
    "main",
    "full",
    "common",
    "natural",
    "significant",
    "similar",
    "hot",
    "dead",
    "central",
    "happy",
    "serious",
    "ready",
    "simple",
    "short",
    "personal",
    "single",
    "medical",
    "alone",
    "cold",
    "popular",
    "basic",
    "traditional",
    "dark",
    "various",
    "entire",
    "past",
    "final",
    "future",
    "wrong",
    "private",
    "social",
    "light",
    "safe",
    "physical",
    "general",
    "environmental",
    "financial",
    "blue",
    "beautiful",
    "specific",
    "primary",
    "individual",
    "potential",
    "professional",
    "international",
    "direct",
  ],

  adverbs: [
    "up",
    "so",
    "out",
    "just",
    "now",
    "how",
    "then",
    "more",
    "also",
    "here",
    "well",
    "only",
    "very",
    "still",
    "even",
    "back",
    "there",
    "down",
    "after",
    "never",
    "always",
    "often",
    "almost",
    "again",
    "already",
    "soon",
    "directly",
    "once",
    "quickly",
    "quite",
    "recently",
    "suddenly",
    "certainly",
    "usually",
    "exactly",
    "finally",
    "nearly",
    "simply",
    "hardly",
    "later",
    "together",
    "likely",
    "especially",
    "either",
    "immediately",
    "actually",
    "alone",
    "sometimes",
    "yesterday",
    "tomorrow",
    "tonight",
    "away",
    "today",
    "far",
    "home",
    "thus",
    "perhaps",
    "therefore",
    "forward",
    "close",
    "indeed",
    "enough",
    "rather",
    "less",
    "ahead",
    "anymore",
    "besides",
    "beyond",
    "clearly",
    "early",
    "elsewhere",
    "everywhere",
    "forever",
    "frequently",
    "however",
    "inside",
    "instead",
    "maybe",
    "meanwhile",
    "mostly",
    "nearby",
    "occasionally",
    "otherwise",
    "outside",
    "rarely",
    "somewhere",
    "twice",
    "whenever",
    "wherever",
    "yet",
  ],

  prepositions: [
    "to",
    "of",
    "in",
    "for",
    "on",
    "with",
    "at",
    "by",
    "from",
    "up",
    "about",
    "into",
    "through",
    "during",
    "before",
    "after",
    "over",
    "between",
    "under",
    "since",
    "without",
    "within",
    "along",
    "following",
    "across",
    "behind",
    "beyond",
    "plus",
    "except",
    "but",
    "out",
    "against",
    "around",
    "among",
    "throughout",
    "despite",
    "towards",
    "upon",
    "off",
    "above",
    "below",
    "including",
    "until",
    "while",
    "via",
    "per",
    "toward",
  ],

  conjunctions: [
    "and",
    "or",
    "but",
    "if",
    "because",
    "as",
    "until",
    "while",
    "although",
    "though",
    "since",
    "unless",
    "so",
    "before",
    "after",
    "when",
    "where",
    "whether",
    "nor",
    "once",
    "whereas",
    "than",
    "whenever",
    "wherever",
    "however",
    "whatever",
    "whoever",
  ],

  commonPhrases: [
    "according to",
    "as well as",
    "in order to",
    "such as",
    "at least",
    "in fact",
    "for example",
    "on the other hand",
    "as a result",
    "at the same time",
  ],
};

// Sentence patterns for generating grammatically correct sentences
export const sentencePatterns = [
  ["article", "adjective", "noun", "verb", "adverb"],
  ["pronoun", "verb", "article", "noun"],
  ["article", "noun", "verb", "adjective"],
  ["pronoun", "adverb", "verb", "article", "adjective", "noun"],
  ["article", "adjective", "noun", "verb", "preposition", "article", "noun"],
  ["pronoun", "verb", "conjunction", "pronoun", "verb"],
  ["adverb", "pronoun", "verb", "article", "noun"],
  ["article", "noun", "verb", "adverb", "adjective"],
  ["pronoun", "verb", "preposition", "article", "adjective", "noun"],
  ["conjunction", "pronoun", "verb", "pronoun", "verb", "adverb"],
];

// Helper function to get a random word from a category
export function getRandomWord(category: keyof typeof commonWords): string {
  const words = commonWords[category];
  return words[Math.floor(Math.random() * words.length)];
}

// Generate a random sentence using patterns
export function generateRandomSentence(): string {
  const pattern =
    sentencePatterns[Math.floor(Math.random() * sentencePatterns.length)];
  const words: string[] = [];

  pattern.forEach((type, index) => {
    let word: string;
    switch (type) {
      case "article":
        word = getRandomWord("articles");
        break;
      case "pronoun":
        word = getRandomWord("pronouns");
        break;
      case "verb":
        word = getRandomWord("verbs");
        // Conjugate some common verbs for present tense third person
        if (
          index > 0 &&
          pattern[index - 1] === "noun" &&
          words[words.length - 1] !== "i" &&
          words[words.length - 1] !== "you"
        ) {
          if (word === "have") word = "has";
          else if (word === "do") word = "does";
          else if (word === "be") word = "is";
          else if (
            ![
              "can",
              "will",
              "would",
              "should",
              "could",
              "might",
              "must",
            ].includes(word)
          ) {
            word = word + "s";
          }
        }
        break;
      case "noun":
        word = getRandomWord("nouns");
        break;
      case "adjective":
        word = getRandomWord("adjectives");
        break;
      case "adverb":
        word = getRandomWord("adverbs");
        break;
      case "preposition":
        word = getRandomWord("prepositions");
        break;
      case "conjunction":
        word = getRandomWord("conjunctions");
        break;
      default:
        word = getRandomWord("nouns");
    }

    // Keep everything lowercase
    words.push(word);
  });

  // Return without punctuation
  return words.join(" ");
}

// Generate a random paragraph with multiple sentences
export function generateRandomParagraph(sentenceCount: number = 3): string {
  const sentences: string[] = [];
  for (let i = 0; i < sentenceCount; i++) {
    sentences.push(generateRandomSentence());
  }
  // Join with spaces, no periods
  return sentences.join(" ");
}
